In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#Sentences
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your video are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your video are good']

In [4]:
#define the vocabulary size

voc_size=10000

In [5]:
#one hot Representation

one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[9439, 3779, 1973, 7309],
 [9439, 3779, 1973, 5966],
 [9439, 4779, 1973, 4341],
 [8368, 5660, 9857, 3879, 2348],
 [8368, 5660, 9857, 3879, 8010],
 [9717, 9439, 2717, 1973, 4119],
 [6007, 9137, 8389, 3879]]

In [7]:
#word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9439 3779 1973 7309]
 [   0    0    0    0 9439 3779 1973 5966]
 [   0    0    0    0 9439 4779 1973 4341]
 [   0    0    0 8368 5660 9857 3879 2348]
 [   0    0    0 8368 5660 9857 3879 8010]
 [   0    0    0 9717 9439 2717 1973 4119]
 [   0    0    0    0 6007 9137 8389 3879]]


In [12]:
#features representaion
dim = 10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 904ms/step


array([[[-0.04196805,  0.03788972,  0.02216258, -0.030828  ,
         -0.00711064,  0.04374888, -0.01778769, -0.01283754,
          0.00358211,  0.02772355],
        [-0.04196805,  0.03788972,  0.02216258, -0.030828  ,
         -0.00711064,  0.04374888, -0.01778769, -0.01283754,
          0.00358211,  0.02772355],
        [-0.04196805,  0.03788972,  0.02216258, -0.030828  ,
         -0.00711064,  0.04374888, -0.01778769, -0.01283754,
          0.00358211,  0.02772355],
        [-0.04196805,  0.03788972,  0.02216258, -0.030828  ,
         -0.00711064,  0.04374888, -0.01778769, -0.01283754,
          0.00358211,  0.02772355],
        [-0.01764036, -0.02859914, -0.00546203,  0.03630215,
         -0.00385667,  0.023569  ,  0.04464353,  0.00034278,
         -0.03162515,  0.04095649],
        [ 0.02635786,  0.0175106 , -0.04558823,  0.02164893,
          0.04818953,  0.00374714,  0.04458118, -0.02274111,
          0.03301561, -0.00642689],
        [-0.03262681, -0.01458117,  0.01756886,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9439, 3779, 1973, 7309])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 243ms/step


array([[-0.04196805,  0.03788972,  0.02216258, -0.030828  , -0.00711064,
         0.04374888, -0.01778769, -0.01283754,  0.00358211,  0.02772355],
       [-0.04196805,  0.03788972,  0.02216258, -0.030828  , -0.00711064,
         0.04374888, -0.01778769, -0.01283754,  0.00358211,  0.02772355],
       [-0.04196805,  0.03788972,  0.02216258, -0.030828  , -0.00711064,
         0.04374888, -0.01778769, -0.01283754,  0.00358211,  0.02772355],
       [-0.04196805,  0.03788972,  0.02216258, -0.030828  , -0.00711064,
         0.04374888, -0.01778769, -0.01283754,  0.00358211,  0.02772355],
       [-0.01764036, -0.02859914, -0.00546203,  0.03630215, -0.00385667,
         0.023569  ,  0.04464353,  0.00034278, -0.03162515,  0.04095649],
       [ 0.02635786,  0.0175106 , -0.04558823,  0.02164893,  0.04818953,
         0.00374714,  0.04458118, -0.02274111,  0.03301561, -0.00642689],
       [-0.03262681, -0.01458117,  0.01756886,  0.00029502,  0.00677716,
         0.00468477, -0.02563623, -0.00724853